/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GuiCattleNetic;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.awt.event.*;
import java.awt.Color;
import java.sql.SQLException;
import javax.naming.spi.DirStateFactory.Result;
import javax.swing.JButton;
import javax.swing.JPanel;
//import javax.swing.JInternalFrame;

/**
 *
 * @author Hamzah Manzoor
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    String url = "jdbc:mysql://localhost:3306/cattleNetic";
    String user = "root";
    String password = "root";
    public Customer() {
        initComponents();
        try {
            String searchID = "1";
            String sql = "SELECT * FROM customer WHERE ID = '" + searchID + "' ";
            //Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, user, password);
            Statement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                String customerName = rs.getString(2);
                CustomerNameLabel.setText(customerName);
                String orderCount = rs.getString(3);
                OrderCountLabel.setText(orderCount);
                
                String subscribtion = rs.getString(4);
                if (subscribtion.equals("0")) {
                    subscribtionLabel.setText("NULL");
                } else {
                    subscribtionLabel.setText(subscribtion + " Ltr(s)");    
                }
                
                String tempType = rs.getString(5);
                String customerType = "";
                int milk = 0;
                int meat = 0;
                if (tempType.equals("1")){
                    milk = 1;
                    //customerType += "Milk"; 
                }
                tempType = rs.getString(7);
                if (tempType.equals("1")) {
                    meat = 1;
                    if (milk == 1)
                        customerType += "Milk & Meat";
                    else {
                        customerType += "      Meat";
                    }
                    
                    
                }
                if (milk == 1 && meat == 0)
                    customerType += "      Milk";
                customerTypeLabel.setText(customerType);
                                
            } else {
                JOptionPane.showMessageDialog(null, "No content in the database");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Issues in SQL syntax", "Database", JOptionPane.ERROR_MESSAGE);
            //System.out.println(ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        OrderManagement = new javax.swing.JButton();
        MeatOrder = new javax.swing.JButton();
        Feedback = new javax.swing.JButton();
        Profile = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        CustomerNameLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        OrderCountLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        subscribtionLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        customerTypeLabel = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Page | Cattle Netic");
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(1551, 830));

        MainPanel.setBackground(new java.awt.Color(204, 204, 255));
        MainPanel.setPreferredSize(new java.awt.Dimension(1551, 830));

        MenuPanel.setBackground(new java.awt.Color(54, 33, 89));
        MenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("CATTLENETIC");
        MenuPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 110, 30));

        jSeparator1.setBackground(new java.awt.Color(255, 204, 102));
        jSeparator1.setForeground(new java.awt.Color(255, 204, 102));
        MenuPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 220, 10));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/external-cow-farming-icongeek26-outline-gradient-icongeek26.png"))); // NOI18N
        MenuPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 120));

        OrderManagement.setBackground(new java.awt.Color(80, 60, 112));
        OrderManagement.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        OrderManagement.setForeground(new java.awt.Color(204, 204, 204));
        OrderManagement.setText("Milk Order Management");
        OrderManagement.setBorder(null);
        OrderManagement.setBorderPainted(false);
        OrderManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderManagementActionPerformed(evt);
            }
        });
        MenuPanel.add(OrderManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 240, 40));

        MeatOrder.setBackground(new java.awt.Color(80, 45, 100));
        MeatOrder.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        MeatOrder.setForeground(new java.awt.Color(204, 204, 204));
        MeatOrder.setText("Meat Order Management");
        MeatOrder.setBorder(null);
        MeatOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeatOrderActionPerformed(evt);
            }
        });
        MenuPanel.add(MeatOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 240, 40));

        Feedback.setBackground(new java.awt.Color(80, 60, 112));
        Feedback.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Feedback.setForeground(new java.awt.Color(204, 204, 204));
        Feedback.setText("Give Feedback");
        Feedback.setBorder(null);
        Feedback.setBorderPainted(false);
        Feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeedbackActionPerformed(evt);
            }
        });
        MenuPanel.add(Feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 240, 40));

        Profile.setBackground(new java.awt.Color(80, 45, 100));
        Profile.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Profile.setForeground(new java.awt.Color(204, 204, 204));
        Profile.setText("Update Profile");
        Profile.setBorder(null);
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });
        MenuPanel.add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 240, 40));

        Logout.setBackground(new java.awt.Color(80, 60, 112));
        Logout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Logout.setForeground(new java.awt.Color(204, 204, 204));
        Logout.setText("Logout");
        Logout.setBorder(null);
        Logout.setBorderPainted(false);
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        MenuPanel.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 90, 40));

        jSeparator2.setBackground(new java.awt.Color(255, 204, 102));
        jSeparator2.setForeground(new java.awt.Color(255, 204, 102));
        MenuPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 220, -1));

        jPanel1.setBackground(new java.awt.Color(110, 89, 222));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CustomerNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CustomerNameLabel.setForeground(new java.awt.Color(204, 204, 204));
        CustomerNameLabel.setText("Customer Name");
        jPanel1.add(CustomerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Customer Portal");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 303, 50));

        jDesktopPane1.setLayout(new java.awt.GridLayout(2, 3));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Order Count");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 0, 2, new java.awt.Color(0, 0, 0)));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jDesktopPane1.add(jLabel4);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Subscribtion");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 0, 2, new java.awt.Color(0, 0, 0)));
        jDesktopPane1.add(jLabel8);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Customer Type");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 0, 2, new java.awt.Color(0, 0, 0)));
        jDesktopPane1.add(jLabel6);

        jPanel4.setBackground(new java.awt.Color(204, 0, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(54, 33, 89)));
        jPanel4.setForeground(new java.awt.Color(54, 33, 89));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrderCountLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        OrderCountLabel.setForeground(new java.awt.Color(255, 255, 255));
        OrderCountLabel.setText("34");
        jPanel4.add(OrderCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, 50));

        jDesktopPane1.add(jPanel4);

        jPanel3.setBackground(new java.awt.Color(0, 153, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(54, 33, 89)));
        jPanel3.setForeground(new java.awt.Color(54, 33, 89));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subscribtionLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        subscribtionLabel.setForeground(new java.awt.Color(255, 255, 255));
        subscribtionLabel.setText("4 Ltr(s)");
        jPanel3.add(subscribtionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 50));

        jDesktopPane1.add(jPanel3);

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(54, 33, 89)));
        jPanel2.setForeground(new java.awt.Color(54, 33, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        customerTypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        customerTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerTypeLabel.setText("Milk");
        jPanel2.add(customerTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 50));

        jDesktopPane1.add(jPanel2);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1262, Short.MAX_VALUE)
                    .addComponent(jDesktopPane2)))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1083, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
        // TODO add your handling code here:
        UpdateProfile profile = new UpdateProfile();
        profile.setVisible(true);
        jDesktopPane2.add(profile);
    }//GEN-LAST:event_ProfileActionPerformed

    private void FeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeedbackActionPerformed
        // TODO add your handling code here:
        FeadBack feadback = new FeadBack();
        feadback.setVisible(true);
        jDesktopPane2.add(feadback);
    }//GEN-LAST:event_FeedbackActionPerformed

    private void MeatOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeatOrderActionPerformed
        // TODO add your handling code here:
        MeatOrderManagement meat = new MeatOrderManagement();
        meat.setVisible(true);
        jDesktopPane2.add(meat); 
    }//GEN-LAST:event_MeatOrderActionPerformed

    private void OrderManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderManagementActionPerformed

        OrderManagement om = new OrderManagement();
        om.setVisible(true);
        jDesktopPane2.add(om);
    }//GEN-LAST:event_OrderManagementActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    void setColor(JPanel panel){
        panel.setBackground(new Color(85, 65, 118));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(64, 43, 100));
    }
    void setColor(JButton panel){
        panel.setBackground(new Color(85, 65, 118));
    }
    
    void resetColor(JButton panel){
        panel.setBackground(new Color(64, 43, 100));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JButton Feedback;
    private javax.swing.JButton Logout;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton MeatOrder;
    private javax.swing.JPanel MenuPanel;
    public javax.swing.JLabel OrderCountLabel;
    private javax.swing.JButton OrderManagement;
    private javax.swing.JButton Profile;
    public javax.swing.JLabel customerTypeLabel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JLabel subscribtionLabel;
    // End of variables declaration//GEN-END:variables
}
