/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GuiCattleNetic;

import java.beans.PropertyVetoException;
import static java.lang.System.exit;
import java.sql.Connection;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hamzah Manzoor
 */
public class MeatOrderManagement extends javax.swing.JInternalFrame {

    /**
     * Creates new form OrderManagement
     */
    String url = "jdbc:mysql://localhost:3306/cattleNetic";
    String user = "root";
    String password = "root";
    String price = "534"; 
    
    public MeatOrderManagement() {
        initComponents();
        MeatPriceLabel.setText(price);
        BillLabel.setText("000 RS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CancelBtn = new javax.swing.JButton();
        PlaceOrderBtn = new javax.swing.JButton();
        OrderSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        MeatPriceLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BillLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 255, 51));
        setClosable(true);
        setTitle("Order Meat");

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));

        CancelBtn.setBackground(new java.awt.Color(80, 45, 100));
        CancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CancelBtn.setForeground(new java.awt.Color(204, 204, 204));
        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        PlaceOrderBtn.setBackground(new java.awt.Color(80, 60, 112));
        PlaceOrderBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PlaceOrderBtn.setForeground(new java.awt.Color(204, 204, 204));
        PlaceOrderBtn.setText("Place Order");
        PlaceOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaceOrderBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("How much kilo of meat would you like to get:");

        MeatPriceLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MeatPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        MeatPriceLabel.setText("500 RS");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("The Current Price of Meat per kilo is:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Your total bill would be: ");

        BillLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BillLabel.setForeground(new java.awt.Color(255, 255, 255));
        BillLabel.setText("1500 RS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(OrderSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(PlaceOrderBtn))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(CancelBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(BillLabel))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(MeatPriceLabel)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MeatPriceLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(OrderSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(BillLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlaceOrderBtn)
                    .addComponent(CancelBtn))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlaceOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaceOrderBtnActionPerformed
        // TODO add your handling code here:
        Object amount = OrderSpinner.getValue();
        
        int total_Bill = Integer.valueOf((int) amount)*Integer.parseInt(price);
        int amount_Ordered = Integer.valueOf((int) amount);
        if (total_Bill < 0) {
            JOptionPane.showMessageDialog(null,"Warning! Amout cannot be negative.","Alert",JOptionPane.WARNING_MESSAGE);
            BillLabel.setText("000 RS");
        } else {
            BillLabel.setText(Integer.toString(total_Bill) + " RS");
            JOptionPane.showMessageDialog(null, "Success! Your order has been placed");
            
            //String bill1 = Integer.toString(bill);
            
            
            //System.out.println("AMT is: " + amt);
            try { 
                
                Connection con = DriverManager.getConnection(url, user, password);
                
                String query = " insert into meatorders (customerID, customerName, amountOrdered, totalBill)"
                    + " values (?, ?, ?, ?)";

      // create the mysql insert preparedstatement
                PreparedStatement preparedStmt = con.prepareStatement(query);
                preparedStmt.setInt    (1, 1);
                preparedStmt.setString (2, "Ahmad Mir");
                preparedStmt.setInt    (3, amount_Ordered);
                preparedStmt.setInt    (4, total_Bill);

                preparedStmt.execute();
                 
                 
                //Statement st = con.createStatement(); 
                //st.executeUpdate("INSERT INTO meatorders " + 
                //    "VALUES (1, 'Ahmad Mir', amountOrdered, totalBill)");

                con.close(); 
            } catch (Exception e) { 
                System.err.println("Got an exception! "); 
                System.err.println(e.getMessage()); 
            }     
        }
    }//GEN-LAST:event_PlaceOrderBtnActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        try {
            // TODO add your handling code here:
            //exit(0);
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MeatOrderManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CancelBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel BillLabel;
    private javax.swing.JButton CancelBtn;
    public javax.swing.JLabel MeatPriceLabel;
    public javax.swing.JSpinner OrderSpinner;
    private javax.swing.JButton PlaceOrderBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
