/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication8;



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Pattern;

import javax.swing.JOptionPane;

/**
 *
 * @author l2013
 */
public class Log extends javax.swing.JFrame {

   

    /**
     * Creates new form Log
     */
    public Log() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        panel1 = new java.awt.Panel();
        tfu = new javax.swing.JTextField();
        tfp = new javax.swing.JTextField();
        Login_As = new javax.swing.JComboBox<>();
        Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        type = new javax.swing.JTextField();
        Select = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        panel2 = new java.awt.Panel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        jButton1.setText("jButton1");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1551, 830));
        setSize(new java.awt.Dimension(1109, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(85, 55, 118));
        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        panel1.setPreferredSize(new java.awt.Dimension(1551, 830));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfu.setBackground(new java.awt.Color(85, 55, 89));
        tfu.setForeground(new java.awt.Color(255, 255, 255));
        tfu.setText("Email");
        tfu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tfu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfuActionPerformed(evt);
            }
        });
        panel1.add(tfu, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 330, 50));

        tfp.setBackground(new java.awt.Color(85, 55, 89));
        tfp.setForeground(new java.awt.Color(255, 255, 255));
        tfp.setText("Password");
        tfp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tfp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpActionPerformed(evt);
            }
        });
        panel1.add(tfp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 330, 50));

        Login_As.setBackground(new java.awt.Color(85, 55, 89));
        Login_As.setForeground(new java.awt.Color(255, 255, 255));
        Login_As.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Employee", "Doctor", "Customer" }));
        Login_As.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_AsActionPerformed(evt);
            }
        });
        panel1.add(Login_As, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, 40));

        Login.setForeground(new java.awt.Color(0, 0, 51));
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        panel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\l2013\\Pictures\\New folder\\external-cow-farming-icongeek26-outline-gradient-icongeek26.png")); // NOI18N
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 160, -1));

        type.setBackground(new java.awt.Color(85, 55, 89));
        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        type.setMinimumSize(new java.awt.Dimension(0, 0));
        type.setPreferredSize(new java.awt.Dimension(1551, 830));
        panel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 120, 30));

        Select.setBackground(new java.awt.Color(85, 55, 89));
        Select.setForeground(new java.awt.Color(255, 255, 255));
        Select.setText("Select");
        Select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectActionPerformed(evt);
            }
        });
        panel1.add(Select, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\l2013\\Pictures\\New folder\\icons8-username-48.png")); // NOI18N
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\l2013\\Pictures\\New folder\\password (1).png")); // NOI18N
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));
        panel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 67, -1, -1));

        jButton2.setText("Forgot Password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, -1, 60));

        jButton4.setText("Create an account");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 590, -1, 50));
        panel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1057, 67, -1, -1));
        panel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        panel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        panel1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1270, 770));

        panel2.setBackground(new java.awt.Color(54, 33, 89));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\l2013\\Pictures\\icons8-email-32.png")); // NOI18N
        panel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CattleNetic@gmail.com");
        panel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("0425678943");
        panel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\l2013\\Pictures\\icons8-phone-24.png")); // NOI18N
        panel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\l2013\\Pictures\\New folder\\external-cow-farming-victoruler-linear-colour-victoruler.png")); // NOI18N
        panel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 250, 210));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 770));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CattleNetic");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 242, 54));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Sighnin Tb =new   Sighnin ();
        Tb.show();
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void SelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectActionPerformed
        // TODO add your handling code here:
        type.setText(     Login_As.getSelectedItem().toString());
    }//GEN-LAST:event_SelectActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:

        String Username = tfu.getText();
        String Password = tfp.getText();
        // String Id= id.getText();
        String type1= type.getText();
        if(!isValid(Username))
        {
            JOptionPane.showMessageDialog(this, "Incorrect Email format. ", "Error ", JOptionPane.ERROR_MESSAGE);
        }
        if(Username.isEmpty()||Password.isEmpty()||type1.isEmpty())
        {

            JOptionPane.showMessageDialog(this, "UserName / Password should not be empty. ", "Error ", JOptionPane.ERROR_MESSAGE);
        }

        else {

            // converting from array to string
            if(validate_login(Username,Password))
            JOptionPane.showMessageDialog(null, "Login Successfully");
            else
            JOptionPane.showMessageDialog(null, "Incorrect Login Credentials");

        }
    }//GEN-LAST:event_LoginActionPerformed

    private void Login_AsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_AsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_AsActionPerformed

    private void tfuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfuActionPerformed

    private void tfpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
              JOptionPane.showMessageDialog(null, "Forget password!");
    }//GEN-LAST:event_jButton2ActionPerformed
private boolean validate_login(String username,String password) {
   
 
   
   try{           
        
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/db","root","root");
            if(con==null)
            {
                
                 System.out.println("There were errors while connecting to db");
            }
            
            else
                    {
                        
                        System.out.println("Connection Successful");
                        
                    }
            
             
     String User_Type = type.getText();
           System.out.println();
    
       if(User_Type.equals("Admin"))
       {
           String S ="select * from db.sighnin where   Email=? and  Password=?";
            
               
            PreparedStatement Ps= con.prepareStatement(S);
           // Ps.setString(1,  id.getText());
            Ps.setString(1,  tfu.getText());
             Ps.setString(2,  tfp.getText());
             ResultSet rs = Ps.executeQuery(); 
          
       if(rs.next())    
          
           return true;    
       else
           return false;       
       }
       
     else  if(User_Type.equals("Employee"))
       {
           
         String  S="select * from db.employee2 where Email=? and  Password=?";
              
            PreparedStatement Ps= con.prepareStatement(S);
           // Ps.setString(1,  id.getText());
            Ps.setString(1,  tfu.getText());
             Ps.setString(2,  tfp.getText());
             ResultSet rs = Ps.executeQuery();                    
       if(rs.next())  {   
               
          CustomerPage C= new CustomerPage();
          Salary salary = new Salary();
       
        C.SetCustomer(rs, User_Type);
          C.setVisible(true);
       setVisible(false);
           return true;    
       }
       else
           return false;       
       }
       
     else if(User_Type.equals("Customer"))
     {
             String  S="select * from db.customer2 where Email=? and  Password=?";
                  
            PreparedStatement Ps= con.prepareStatement(S);
           // Ps.setString(1,  id.getText());
            Ps.setString(1,  tfu.getText());
             Ps.setString(2,  tfp.getText());
             ResultSet rs = Ps.executeQuery();    
             
          
       if(rs.next())   
       { 
           return true; 
       }
       else
           return false;       
           
         
     }
          
     else if(User_Type.equals("Doctor"))
     {
          String     S="select * from db.doctor where   Email=? and  Password=?";
              
            PreparedStatement Ps= con.prepareStatement(S);
           // Ps.setString(1,  id.getText());
            Ps.setString(1,  tfu.getText());
             Ps.setString(2,  tfp.getText());
             ResultSet rs = Ps.executeQuery();                    
       if(rs.next())    
          
           return true;    
       else
           return false;       
         
     }
       
     
      
         
   }  
   
   catch(Exception e){
       e.printStackTrace();
   
   }    
   
    
   
        return false;
}


  public static boolean isValid(String email)
    {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+
                            "[a-zA-Z0-9_+&*-]+)*@" +
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" +
                            "A-Z]{2,7}$";
                              
        Pattern pat = Pattern.compile(emailRegex);
        if (email == null)
            return false;
        return pat.matcher(email).matches();
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JComboBox<String> Login_As;
    private javax.swing.JButton Select;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JTextField tfp;
    private javax.swing.JTextField tfu;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
