/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication8;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author l2013
 */
public class Salary extends javax.swing.JFrame {

    /**
     * Creates new form Salary
     */
    String Name;
    public Salary() {
        initComponents();
    }
  
    public void Setname(String N)
    {
        Name =N;
    }
    public String GetName()
    {
        return Name;
    }
    
    void SetUSER (String Value, String  Salary) throws SQLException
  {
     // JOB.setText(User_Type);
     txtname.setText(Value);
      txtsal.setText(Salary);
      
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtname = new javax.swing.JTextField();
        txtetf = new javax.swing.JTextField();
        txtnsal = new javax.swing.JTextField();
        chketf = new javax.swing.JCheckBox();
        chkepf = new javax.swing.JCheckBox();
        txtsal = new javax.swing.JTextField();
        txtallow = new javax.swing.JTextField();
        txtepf = new javax.swing.JTextField();
        txtgsal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jLabel6.setText("jLabel6");

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setPreferredSize(new java.awt.Dimension(1551, 830));

        jPanel1.setBackground(new java.awt.Color(85, 55, 118));
        jPanel1.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jPanel1.setPreferredSize(new java.awt.Dimension(1551, 830));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(null);

        txtname.setBackground(new java.awt.Color(102, 0, 102));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtname);
        txtname.setBounds(150, 160, 210, 30);

        txtetf.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.add(txtetf);
        txtetf.setBounds(150, 310, 220, 29);

        txtnsal.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.add(txtnsal);
        txtnsal.setBounds(160, 580, 210, 30);

        chketf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chketf.setForeground(new java.awt.Color(255, 255, 255));
        chketf.setText("ETF");
        jPanel1.add(chketf);
        chketf.setBounds(50, 310, 60, 31);

        chkepf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chkepf.setForeground(new java.awt.Color(255, 255, 255));
        chkepf.setText("ETF");
        jPanel1.add(chkepf);
        chkepf.setBounds(50, 370, 60, 31);

        txtsal.setBackground(new java.awt.Color(102, 0, 102));
        txtsal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtsal);
        txtsal.setBounds(150, 230, 210, 29);

        txtallow.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.add(txtallow);
        txtallow.setBounds(160, 460, 210, 30);

        txtepf.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.add(txtepf);
        txtepf.setBounds(150, 370, 220, 29);

        txtgsal.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.add(txtgsal);
        txtgsal.setBounds(160, 520, 210, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 160, 70, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Salary");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 230, 90, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Grossay");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 460, 80, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Allowance");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 520, 90, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Net Salary");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 570, 100, 40);

        jButton1.setBackground(new java.awt.Color(102, 0, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(60, 680, 180, 50);

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Employee Salary ");

        jButton3.setText("Go to Customer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\l2013\\Pictures\\New folder\\external-cow-farming-icongeek26-outline-gradient-icongeek26.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(552, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(346, 346, 346)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton3))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(205, 205, 205))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1630, 150);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\l2013\\Pictures\\calculator.png")); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(810, 160, 580, 512);

        jButton2.setBackground(new java.awt.Color(102, 0, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Generate Slip");
        jPanel1.add(jButton2);
        jButton2.setBounds(290, 680, 160, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1631, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 double sal,etf,epf,etfamount,epfamount,gsal,allow,nsal;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
       sal = Double.parseDouble(txtsal.getText());
        
        if(chketf.isSelected()== true)
        {
            etfamount = sal * 10/100;
        }
         if(chketf.isSelected()== true)
        {
            epfamount = sal * 5/100;
        }
        
         txtetf.setText(String.valueOf(etfamount));
         txtepf.setText(String.valueOf(epfamount));
        
        
         gsal = sal - (etfamount +  epfamount);
        
        txtgsal.setText(String.valueOf(gsal));
        
              
        
        if(sal > 50000)
        {
            allow = 2000;
        }
        else if(sal > 30000)
        {
            allow = 1000;
        }
       else
        {
            allow = 0;
        }
        
        txtallow.setText(String.valueOf(allow));
        
        nsal = gsal + allow;
             txtnsal.setText(String.valueOf(nsal));
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          // TODO add your handling code here:
          CustomerPage C= new CustomerPage();
          C.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkepf;
    private javax.swing.JCheckBox chketf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtallow;
    private javax.swing.JTextField txtepf;
    private javax.swing.JTextField txtetf;
    private javax.swing.JTextField txtgsal;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnsal;
    private javax.swing.JTextField txtsal;
    // End of variables declaration//GEN-END:variables
}
