/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication8;

import java.sql.Connection;
import java.sql.DriverManager;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author l2013
 */
public class Sighnin extends javax.swing.JFrame {

    /**
     * Creates new form Sighnin
     */
    public Sighnin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Name = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        Rewrite = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        type = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Add = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        Password = new javax.swing.JTextField();
        Dob = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel2.setBackground(new java.awt.Color(54, 33, 89));
        panel2.setPreferredSize(new java.awt.Dimension(1551, 830));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\l2013\\Pictures\\icons8-email-32.png")); // NOI18N
        panel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CattleNetic@gmail.com");
        panel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("0425678943");
        panel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 672, 90, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\l2013\\Pictures\\icons8-phone-24.png")); // NOI18N
        panel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CattleNetic");
        panel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 242, 54));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\l2013\\Pictures\\New folder\\external-cow-farming-victoruler-linear-colour-victoruler.png")); // NOI18N
        panel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 170, 240));

        jPanel3.setBackground(new java.awt.Color(85, 55, 118));
        jPanel3.setLayout(null);

        Name.setBackground(new java.awt.Color(85, 55, 89));
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Full Name");
        Name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        jPanel3.add(Name);
        Name.setBounds(180, 170, 330, 30);

        Email.setBackground(new java.awt.Color(85, 55, 89));
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email");
        Email.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.add(Email);
        Email.setBounds(180, 220, 330, 30);

        Phone.setBackground(new java.awt.Color(85, 55, 89));
        Phone.setForeground(new java.awt.Color(255, 255, 255));
        Phone.setText("Phonenumber");
        Phone.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneActionPerformed(evt);
            }
        });
        jPanel3.add(Phone);
        Phone.setBounds(190, 280, 320, 30);

        Rewrite.setBackground(new java.awt.Color(85, 55, 89));
        Rewrite.setForeground(new java.awt.Color(255, 255, 255));
        Rewrite.setText("Rewrite Password");
        Rewrite.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Rewrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RewriteActionPerformed(evt);
            }
        });
        jPanel3.add(Rewrite);
        Rewrite.setBounds(650, 230, 320, 30);

        jComboBox1.setBackground(new java.awt.Color(85, 55, 89));
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "Customer", "Doctor", "Admin" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(660, 350, 120, 40);

        jButton2.setBackground(new java.awt.Color(85, 55, 89));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Click me");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(800, 349, 100, 40);

        type.setBackground(new java.awt.Color(85, 55, 89));
        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel3.add(type);
        type.setBounds(690, 410, 110, 23);

        Add.setBackground(new java.awt.Color(85, 55, 89));
        Add.setColumns(20);
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setRows(5);
        Add.setText("Address");
        jScrollPane3.setViewportView(Add);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(200, 360, 310, 40);

        jButton3.setBackground(new java.awt.Color(85, 55, 89));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SignUp");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(620, 580, 130, 50);

        jButton4.setBackground(new java.awt.Color(85, 55, 89));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(290, 580, 130, 50);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(210, 100, 0, 4);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(250, 100, 0, 4);
        jPanel3.add(jSeparator3);
        jSeparator3.setBounds(190, 320, 320, 20);
        jPanel3.add(jSeparator7);
        jSeparator7.setBounds(690, 440, 100, 22);
        jPanel3.add(jLabel4);
        jLabel4.setBounds(210, 20, 160, 0);

        Password.setBackground(new java.awt.Color(85, 55, 89));
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        Password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.add(Password);
        Password.setBounds(640, 160, 330, 40);

        Dob.setBackground(new java.awt.Color(85, 55, 89));
        Dob.setForeground(new java.awt.Color(255, 255, 255));
        Dob.setText("date of birth");
        Dob.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DobActionPerformed(evt);
            }
        });
        jPanel3.add(Dob);
        Dob.setBounds(650, 283, 330, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\l2013\\Pictures\\New folder\\external-cow-farming-icongeek26-outline-gradient-icongeek26.png")); // NOI18N
        jPanel3.add(jLabel2);
        jLabel2.setBounds(500, 10, 230, 150);
        jPanel3.add(jSeparator11);
        jSeparator11.setBounds(180, 210, 330, 20);
        jPanel3.add(jSeparator12);
        jSeparator12.setBounds(660, 270, 320, 30);
        jPanel3.add(jSeparator13);
        jSeparator13.setBounds(660, 330, 330, 40);
        jPanel3.add(jSeparator14);
        jSeparator14.setBounds(190, 260, 320, 30);
        jPanel3.add(jSeparator15);
        jSeparator15.setBounds(650, 210, 320, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\l2013\\Pictures\\icons8-username-48.png")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(110, 170, 48, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\l2013\\Pictures\\icons8-password-48.png")); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(580, 160, 50, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\l2013\\Pictures\\icons8-phone-32.png")); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(120, 270, 40, 60);

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\l2013\\Pictures\\icons8-birth-date-48.png")); // NOI18N
        jPanel3.add(jLabel16);
        jLabel16.setBounds(590, 280, 60, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\l2013\\Pictures\\user (2).png")); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(600, 350, 50, 50);

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\l2013\\Pictures\\order-delivered (2).png")); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(120, 360, 56, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\l2013\\Pictures\\icons8-envelope-24.png")); // NOI18N
        jPanel3.add(jLabel15);
        jLabel15.setBounds(120, 210, 50, 50);
        jPanel3.add(jSeparator8);
        jSeparator8.setBounds(200, 410, 310, 40);

        panel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 0, 1100, 810));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        type.setText(jComboBox1.getSelectedItem().toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
   
         
      String Name1=   Name.getText();
      String Email1=  Email.getText();
       String Dob1= Dob.getText();
       String Phone1= Phone.getText();
        String Password1=Password.getText();
        String Pas=Rewrite.getText();
         String type1=type.getText();
        String Add1= Add.getText();
       // String Id= id.getText();
        // int number = Integer.parseInt(Id);
        
         if(!isValid(Email1))
      {
           JOptionPane.showMessageDialog(this, "Incorrect Email format. ", "Error ", JOptionPane.ERROR_MESSAGE);
      }
      if(Name1.isEmpty()||Email1.isEmpty()||Dob1.isEmpty()|| Phone1.isEmpty()|| Password1.isEmpty()|| Pas.isEmpty()|| type1.isEmpty()||Add1.isEmpty())
        {
            
              JOptionPane.showMessageDialog(this, "UserName / Password / Dob /Phone / Password / type1 should not be empty. ", "Error ", JOptionPane.ERROR_MESSAGE);
        }
          
          else {
          
          
            
             
    try {
        new com.mysql.jdbc.Driver();
       Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/db","root","root");
              String User_Type = type.getText();
        
    if(User_Type.equals("Admin"))
    {
          java.sql.PreparedStatement insert = null;
          String queryString = "insert into db.sighnin(UserName,Email,Dob,Password,Rewrite,number,Type,Address)values (?,?,?,?,?,?,?,?)";
     //   con.setAutoCommit(false);
        insert = con.prepareStatement(queryString);

        insert.setString(1,Name.getText()   );
        insert.setString(2, Email.getText());
        insert.setString(3, Dob.getText());
        insert.setString(4,Phone.getText());
        insert.setString(5,Password.getText());
        insert.setString(6, Rewrite.getText());
        insert.setString(7,type.getText());
        insert.setString(8, Add.getText());
        insert.executeUpdate();
          //ResultSet rs = insert.executeQuery();                    
        JOptionPane.showMessageDialog(this,"Succesfully Inserted");
        con.close();
        
    }
      
          
    if(User_Type.equals("Customer"))
    {

          String queryString = "insert into db.customer2(UserName,Email,Dob,Password,Rewrite,number,Type,Address)values (?,?,?,?,?,?,?,?)";
     //   con.setAutoCommit(false);
           java.sql.PreparedStatement insert = con.prepareStatement(queryString);
     insert.setString(1,Name.getText()   );
        insert.setString(2, Email.getText());
        insert.setString(3, Dob.getText());
        insert.setString(4,Phone.getText());
        insert.setString(5,Password.getText());
        insert.setString(6, Rewrite.getText());
        insert.setString(7,type.getText());
        insert.setString(8, Add.getText());
      //    insert.executeUpdate("insert into donors (UserName,Email,Dob,Password,Rewrite,number,Type,Address) values('"+d_unit+"','"+d_name+"','"+d_dob+"','"+d_age+"','"+d_doorno+"','"+d_street+"','"+d_vc+"','"+d_district+"','"+d_pin+"','"+d_phone+"','"+d_mail+"','"+d_occupations+"')");
        int n1 =insert.executeUpdate();
        if(n1>0)
          //ResultSet rs = insert.executeQuery();                    
        {  JOptionPane.showMessageDialog(this,"Succesfully Inserted");
        
        
        }
        con.close();
        
    }
    
     if(User_Type.equals("Employee"))
    {
        //  java.sql.PreparedStatement insert = null;
          String queryString = "insert into db.employee2(UserName,Email,Dob,Password,Rewrite,number,Type,Address)values (?,?,?,?,?,?,?,?)";
      //  con.setAutoCommit(false);
           java.sql.PreparedStatement insert= con.prepareStatement(queryString);

        insert.setString(1,Name.getText()   );
        insert.setString(2, Email.getText());
        insert.setString(3, Dob.getText());
           insert.setString(4,Password.getText());
               insert.setString(5, Rewrite.getText());
        insert.setString(6,Phone.getText());
     
 
        insert.setString(7,type.getText());
        insert.setString(8, Add.getText());
      int n1 =insert.executeUpdate();
        if(n1>0)
          //ResultSet rs = insert.executeQuery();                    
        {  JOptionPane.showMessageDialog(this,"Succesfully Inserted");
        
        
        }
        con.close();
        
    }
     
     
      if(User_Type.equals("Doctor"))
    {
       
          String queryString = "insert into db.doctor22(UserName,Email,Dob,Password,Rewrite,number,Type,Address)values (?,?,?,?,?,?,?,?)";
       // con.setAutoCommit(false);
         java.sql.PreparedStatement insert  = con.prepareStatement(queryString);

        insert.setString(1,Name.getText()   );
        insert.setString(2, Email.getText());
        insert.setString(3, Dob.getText());
        insert.setString(4,Phone.getText());
        insert.setString(5,Password.getText());
        insert.setString(6, Rewrite.getText());
        insert.setString(7,type.getText());
        insert.setString(8, Add.getText());
        int n1 =insert.executeUpdate();
        if(n1>0)
          //ResultSet rs = insert.executeQuery();                    
        {  JOptionPane.showMessageDialog(this,"Succesfully Inserted");
        
        
        }
        
    }
    
    } 
    
  
   
    catch (Exception e) {
        e.printStackTrace();
      
    } 
        
       
     
      
    
        
    }                    
    }//GEN-LAST:event_jButton3ActionPerformed

    public static boolean isValid(String email)
    {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+
                            "[a-zA-Z0-9_+&*-]+)*@" +
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" +
                            "A-Z]{2,7}$";
                              
        Pattern pat = Pattern.compile(emailRegex);
        if (email == null)
            return false;
        return pat.matcher(email).matches();
    }
    
    
    private void DobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DobActionPerformed

    private void PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneActionPerformed

    private void RewriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RewriteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RewriteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Log L1= new Log();
        L1.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sighnin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sighnin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sighnin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sighnin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sighnin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Add;
    private javax.swing.JTextField Dob;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField Rewrite;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private java.awt.Panel panel2;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
